name: Django tests
on: push 
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Python setup
              uses: actions/setup-python@v4

            - name: Install deps
              run: pip install -r requirements.txt
            
            - name: Test
              run: |
                cd kingdom
                python manage.py migrate
                python manage.py test